filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/hostlog/syslog
    - /var/hostlog/mail.log
    - /var/hostlog/telegraf-alerts.log

output.logstash:
  hosts: ["logstash:5044"]

processors:
 - drop_event:
     when:
        regexp:
           message: "^DBG:"
