
version: '3.4'
services:
  portainer:
    image: portainer/portainer
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /nfsdata/portainer:/data
    restart: always
