
es_host: elasticsearch
use_ssl: false
verify_certs: false
es_port: 9200
run_every:
  minutes: 1
rules_folder: /opt/elastalert/rules
# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status
# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2
# Option basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword
# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 15
