# https://github.com/elastic/elasticsearch-docker
# Need version 5 for elastalert
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
#FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.4


# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
#RUN elasticsearch-plugin --batch install x-pack
