#!/bin/bash

cd /data
mkdir metrics 2>/dev/null
nohup python -m SimpleHTTPServer 8080 >/dev/null 2>&1 &

while sleep 15
do

cat /dev/null > /data/newmetrics
DATUM="`%Y.%m.%d`"

curl -s -X GET http://elasticsearch:9200/filebeat-*-${DATUM}/_search -H 'Content-Type: application/json' -d "
{
     \"from\" : 0, \"size\" : 1000,
     \"query\": {
         \"range\" : {
             \"@timestamp\" : {
                 \"gte\" : \"now-3m\",
                 \"lt\" :  \"now\"
             }
         }
     }
 }" | jq .hits.hits[]._source.log | sed 's/ /_/g' | sed 's/"/+/g' > /data/last3min.txt

for line in `cat searches | sed 's/ /_/g' | sed 's/"/+/g'`
do
COUNT=`grep -c -i ${line} /data/last3min.txt`

echo "logsrch_${line}" | sed "s/\$/ ${COUNT}/" > /data/output

cat /data/output >> /data/newmetrics

done
cp /data/newmetrics /data/metrics/index.html

done
