filebeat.prospectors:
- type: log
  paths:
   - '/var/lib/docker/containers/*/*.log'
   - '/var/hostlog/messages'
  exclude_lines: ['influxdb','filebeater','kibana','telegraf','HTTP/1.1" 2','^\[I\]','json.go:32: ERR Error decoding JSON','metrics.go:39','chronograf','level=info msg=','"url":"/logtrail']
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata: ~
  - drop_event:
      when:
        contains:
          docker.container.image: ceph/daemon
  - drop_event:
      when:
        contains:
          docker.container.labels.com.docker.swarm.service.name: yzer-elkstack_kibana
  - drop_event:
      when:
        contains:
          docker.container.labels.com.docker.swarm.service.name: yzer-elkstack_chronograf
  - drop_event:
      when:
        contains:
          docker.container.labels.com.docker.swarm.service.name: yzer-elkstack_telegraf
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
