filebeat.prospectors:
- type: log
  paths:
   - '/var/lib/docker/containers/*/*.log'
   - '/var/hostlog/messages'
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata: ~
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
